---
- name: Install cmatrix on Ubuntu  
  hosts: localhost # Change this to your target host or group
  become: true # Use become to run as root
  gather_facts: true # Gather facts to get system information
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600  # 1 hour

    - name: Install cmatrix
      ansible.builtin.apt:
        name: cmatrix
        state: present
