---
- name: Install cmatrix on Ubuntu
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600  # 1 hour

    - name: Install cmatrix
      ansible.builtin.apt:
        name: cmatrix
        state: present
